const sharedConfig = require('@2hands/tailwind-config')

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Light mode colors - from shared config
        background: sharedConfig.colors.light.background,
        foreground: sharedConfig.colors.light.foreground,
        card: sharedConfig.colors.light.card,
        'card-foreground': sharedConfig.colors.light['card-foreground'],
        popover: sharedConfig.colors.light.popover,
        'popover-foreground': sharedConfig.colors.light['popover-foreground'],
        primary: sharedConfig.colors.light.primary,
        'primary-foreground': sharedConfig.colors.light['primary-foreground'],
        secondary: sharedConfig.colors.light.secondary,
        'secondary-foreground': sharedConfig.colors.light['secondary-foreground'],
        muted: sharedConfig.colors.light.muted,
        'muted-foreground': sharedConfig.colors.light['muted-foreground'],
        accent: sharedConfig.colors.light.accent,
        'accent-foreground': sharedConfig.colors.light['accent-foreground'],
        destructive: sharedConfig.colors.light.destructive,
        border: sharedConfig.colors.light.border,
        input: sharedConfig.colors.light.input,
        ring: sharedConfig.colors.light.ring,
        sidebar: sharedConfig.colors.light.sidebar,
        'sidebar-foreground': sharedConfig.colors.light['sidebar-foreground'],
        'sidebar-primary': sharedConfig.colors.light['sidebar-primary'],
        'sidebar-primary-foreground': sharedConfig.colors.light['sidebar-primary-foreground'],
        'sidebar-accent': sharedConfig.colors.light['sidebar-accent'],
        'sidebar-accent-foreground': sharedConfig.colors.light['sidebar-accent-foreground'],
        'sidebar-border': sharedConfig.colors.light['sidebar-border'],
        'sidebar-ring': sharedConfig.colors.light['sidebar-ring'],
        // Chart colors
        'chart-1': sharedConfig.colors.chart[1],
        'chart-2': sharedConfig.colors.chart[2],
        'chart-3': sharedConfig.colors.chart[3],
        'chart-4': sharedConfig.colors.chart[4],
        'chart-5': sharedConfig.colors.chart[5],
        // Semantic
        success: sharedConfig.colors.semantic.success,
        error: sharedConfig.colors.semantic.error,
        warning: sharedConfig.colors.semantic.warning,
        info: sharedConfig.colors.semantic.info,
        // Dark mode colors (for dark: variants)
        'dark-background': sharedConfig.colors.dark.background,
        'dark-foreground': sharedConfig.colors.dark.foreground,
        'dark-card': sharedConfig.colors.dark.card,
        'dark-card-foreground': sharedConfig.colors.dark['card-foreground'],
        'dark-primary': sharedConfig.colors.dark.primary,
        'dark-primary-foreground': sharedConfig.colors.dark['primary-foreground'],
        'dark-secondary': sharedConfig.colors.dark.secondary,
        'dark-muted': sharedConfig.colors.dark.muted,
        'dark-muted-foreground': sharedConfig.colors.dark['muted-foreground'],
        'dark-accent': sharedConfig.colors.dark.accent,
        'dark-border': sharedConfig.colors.dark.border,
        'dark-input': sharedConfig.colors.dark.input,
        'dark-ring': sharedConfig.colors.dark.ring,
        'dark-sidebar': sharedConfig.colors.dark.sidebar,
        'dark-sidebar-foreground': sharedConfig.colors.dark['sidebar-foreground'],

        // Semantic token aliases (light defaults)
        'bg-primary': sharedConfig.colors.semanticTokens.light['bg-primary'],
        'bg-secondary': sharedConfig.colors.semanticTokens.light['bg-secondary'],
        'bg-tertiary': sharedConfig.colors.semanticTokens.light['bg-tertiary'],
        'bg-elevated': sharedConfig.colors.semanticTokens.light['bg-elevated'],
        'surface-default': sharedConfig.colors.semanticTokens.light['surface-default'],
        'surface-hover': sharedConfig.colors.semanticTokens.light['surface-hover'],
        'surface-active': sharedConfig.colors.semanticTokens.light['surface-active'],
        'surface-selected': sharedConfig.colors.semanticTokens.light['surface-selected'],
        'text-primary': sharedConfig.colors.semanticTokens.light['text-primary'],
        'text-secondary': sharedConfig.colors.semanticTokens.light['text-secondary'],
        'text-tertiary': sharedConfig.colors.semanticTokens.light['text-tertiary'],
        'border-default': sharedConfig.colors.semanticTokens.light['border-default'],
        'border-medium': sharedConfig.colors.semanticTokens.light['border-medium'],
        'border-focus': sharedConfig.colors.semanticTokens.light['border-focus'],

        // Dark semantic token aliases (for dark variants)
        'dark-bg-primary': sharedConfig.colors.semanticTokens.dark['bg-primary'],
        'dark-bg-secondary': sharedConfig.colors.semanticTokens.dark['bg-secondary'],
        'dark-bg-tertiary': sharedConfig.colors.semanticTokens.dark['bg-tertiary'],
        'dark-surface-default': sharedConfig.colors.semanticTokens.dark['surface-default'],
        'dark-surface-hover': sharedConfig.colors.semanticTokens.dark['surface-hover'],
        'dark-text-primary': sharedConfig.colors.semanticTokens.dark['text-primary'],
        'dark-text-secondary': sharedConfig.colors.semanticTokens.dark['text-secondary'],
        'dark-border-default': sharedConfig.colors.semanticTokens.dark['border-default'],
        'dark-border-focus': sharedConfig.colors.semanticTokens.dark['border-focus'],
      },
      borderRadius: {
        'sm': '4px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
        '2xl': '24px',
        '3xl': '32px',
      },
      fontFamily: {
        sans: sharedConfig.fontFamily.sans,
      },
      fontSize: {
        'xs': '11px',
        'sm': '13px',
        'base': '14px',
        'lg': '16px',
        'xl': '18px',
        '2xl': '24px',
        '3xl': '32px',
        '4xl': '40px',
      },
    },
  },
  plugins: [],
}

